create table tab_cadastro (id integer generated by default as identity, nome varchar(255), primary key (id));
create table tab_endereco (id integer generated by default as identity, logradouro varchar(255), numero varchar(255), primary key (id));
create table tab_perfil (cliente boolean not null, fornecedor boolean not null, id integer generated by default as identity, prestador boolean not null, primary key (id));
